# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b55861b3b1e73c0ef25a4eea66edc8a0460c3ac30b73a8b8a81a3a9d81cf056a697423d972abd75bb34cb1bba81401bef45b5bb5ff322b2ec488d906f5d73bcc

test:
  secret_key_base: f169c0f1cd764e4ba27def5910c0b7cf19332ec7bd6834cafce557b45785cbe7e25014cc59ee1df58a587352c172c5eaf09c3795f88dc7139d792dd22b0486d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
